## Color Definitions
# -> https://www.calmar.ws/vim/256-xterm-24bit-rgb-color-chart.html
PROMPT_COL_BASE="81"
PROMPT_COL_JOBS="171"
PROMPT_COL_GLYPH="48"
PROMPT_COL_PWD="153"
PROMPT_COL_GIT="48"
PROMPT_COL_REPO="48"
PROMPT_COL_BRANCH="48"
PROMPT_COL_STAT_OK="83"
PROMPT_COL_STAT_ATTENTION="227"
PROMPT_COL_STAT_WARN="209"
PROMPT_COL_STAT_ERROR="203"
